---
- hosts: wordpress
  become: true
  tasks:
    - name: Download WordPress tarball
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress to web root
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Remove default index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Set permissions for Apache
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        state: directory
        recurse: yes
